import { useState } from 'react';
import { Download, Loader2 } from 'lucide-react';
import { useAppStore } from '../../store/useAppStore.js';

export default function ExportButton() {
  const { currentSession, messages, sources } = useAppStore();
  const [isExporting, setIsExporting] = useState(false);

  const handleExport = async () => {
    if (!currentSession || isExporting) return;
    setIsExporting(true);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF();

      const diseaseKebab = (currentSession.disease || 'research').toLowerCase().replace(/\s+/g, '-');
      const filename = `curalink-${diseaseKebab}.pdf`;

      // Title
      doc.setFontSize(22);
      doc.setTextColor(15, 23, 42);
      doc.text('Research Brief', 20, 22);

      doc.setFontSize(13);
      doc.setTextColor(37, 99, 235);
      doc.text(currentSession.disease || 'Medical Research', 20, 32);

      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.text(`Generated by Curalink · ${new Date().toLocaleDateString()}`, 20, 40);

      const loc = [currentSession.location?.city, currentSession.location?.country]
        .filter(Boolean)
        .join(', ');
      if (loc) doc.text(`Location context: ${loc}`, 20, 46);

      // Divider
      doc.setDrawColor(226, 232, 240);
      doc.line(20, 50, 190, 50);

      let yPos = 58;
      const lastAnswer = [...messages]
        .reverse()
        .find((m) => m.role === 'assistant' && m.structuredAnswer)?.structuredAnswer;

      if (lastAnswer) {
        if (lastAnswer.condition_overview) {
          doc.setFontSize(13);
          doc.setTextColor(15, 23, 42);
          doc.text('Overview', 20, yPos);
          yPos += 7;
          doc.setFontSize(10);
          doc.setTextColor(51, 65, 85);
          const split = doc.splitTextToSize(lastAnswer.condition_overview, 170);
          doc.text(split, 20, yPos);
          yPos += split.length * 5 + 10;
        }

        if (lastAnswer.research_insights?.length > 0) {
          if (yPos > 250) { doc.addPage(); yPos = 20; }
          doc.setFontSize(13);
          doc.setTextColor(15, 23, 42);
          doc.text('Key Findings', 20, yPos);
          yPos += 7;
          lastAnswer.research_insights.slice(0, 5).forEach((ins) => {
            if (yPos > 270) { doc.addPage(); yPos = 20; }
            doc.setFontSize(10);
            doc.setTextColor(51, 65, 85);
            const text = `• [${ins.type}] ${ins.insight}`;
            const split = doc.splitTextToSize(text, 170);
            doc.text(split, 20, yPos);
            yPos += split.length * 5 + 3;
          });
          yPos += 6;
        }

        if (lastAnswer.recommendations) {
          if (yPos > 250) { doc.addPage(); yPos = 20; }
          doc.setFontSize(13);
          doc.setTextColor(15, 23, 42);
          doc.text('Clinical Guidance', 20, yPos);
          yPos += 7;
          doc.setFontSize(10);
          doc.setTextColor(51, 65, 85);
          const split = doc.splitTextToSize(lastAnswer.recommendations, 170);
          doc.text(split, 20, yPos);
          yPos += split.length * 5 + 10;
        }
      }

      if (sources?.length > 0) {
        if (yPos > 250) { doc.addPage(); yPos = 20; }
        doc.setFontSize(13);
        doc.setTextColor(15, 23, 42);
        doc.text('Sources', 20, yPos);
        yPos += 7;
        sources.slice(0, 8).forEach((src, idx) => {
          if (yPos > 270) { doc.addPage(); yPos = 20; }
          doc.setFontSize(9);
          doc.setTextColor(71, 85, 105);
          const text = `${idx + 1}. [${src.source || src.type}] ${src.title || 'Untitled'} (${src.year || 'N/A'})`;
          const split = doc.splitTextToSize(text, 170);
          doc.text(split, 20, yPos);
          yPos += split.length * 4.5 + 2;
        });
      }

      // Footer
      const pageCount = doc.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text('Curalink — AI-powered medical research', 20, 289);
        doc.text(`${i} / ${pageCount}`, 185, 289, { align: 'right' });
      }

      doc.save(filename);
    } catch (err) {
      console.error('PDF export failed:', err);
    } finally {
      setIsExporting(false);
    }
  };

  const disabled = isExporting || !currentSession;

  return (
    <button
      type="button"
      onClick={handleExport}
      disabled={disabled}
      className="w-full flex items-center justify-center gap-2 text-xs font-semibold rounded-xl px-3 py-2.5 transition-all disabled:opacity-40"
      style={{
        background: 'var(--color-surface-2)',
        border: '1px solid var(--color-border)',
        color: 'var(--text-secondary)',
      }}
      onMouseEnter={(e) => {
        if (!disabled) {
          e.currentTarget.style.borderColor = 'rgba(96,165,250,0.4)';
          e.currentTarget.style.color = '#60a5fa';
        }
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.borderColor = 'var(--color-border)';
        e.currentTarget.style.color = 'var(--text-secondary)';
      }}
    >
      {isExporting ? (
        <Loader2 className="h-3.5 w-3.5 animate-spin" />
      ) : (
        <Download className="h-3.5 w-3.5" />
      )}
      {isExporting ? 'Generating PDF…' : 'Export Research Brief PDF'}
    </button>
  );
}
